### ISSUE TITLE
[BUG] Local Object Detection App Does Not Start Successfully

### ISSUE THREAD

**Issue by wilyle** [eclipse-chariott/chariott#146]
The local object detection app does not start successfully, whether it's run in isolation or as part of the dog mode demo application.

## Expected Behavior
Local object detection app starts up successfully, analyzes the camera feed, and updates the dog mode state

## Current Behavior
Local object detection app fails during startup. This seems to be related to loading the model (`examples/applications/local-object-detection/models/ssd_mobilenet_v1_coco.pb`). See the logs section for more details.

## Steps to Reproduce

1. Start the local object detection app (either by itself or via the dog mode demo script)
2. Wait for a few seconds for the application to attempt the startup process
3. Check the application logs at `target/logs/local_object_detection_app.txt`

## Context (Environment)

Observed in both Ubuntu 22.04 in WSL2 and Ubuntu 20.04 in a Hyper-V VM. Both instances were hosted on a Windows 11 machine

## Logs
```
$ cat target/logs/local_object_detection_app.txt
2023-06-26T20:28:18.320779Z  INFO local_object_detection_app: Application application listening: http://localhost:50061/
2023-06-26T20:28:18.359722Z  INFO examples_common::chariott::registration: Registered with Chariott runtime: RegisterRequest { service: Some(IntentServiceRegistration { name: "sdv.local-detection", version: "0.0.1", url: "http://localhost:50061/", locality: Local }), intents: [IntentRegistration { namespace: "sdv.detection", intent: Inspect }, IntentRegistration { namespace: "sdv.detection", intent: Invoke }] }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: {inner:0x55db6ecca650, InvalidArgument: Invalid GraphDef}', examples/applications/local-object-detection/src/detection.rs:30:70
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Additional Information
N/A

**Comment by ladatz** [comment]
I was able to repro this issue. Needs more investigation

**Comment by Prem-Kumar16** [comment]
I am also facing the same issue running local object detection on Ubuntu 22.04 LTS on AWS ec2 instance. Any solutions for that?

**Comment by ladatz** [comment]
Hi @Prem-Kumar16 , An update was pushed to update the model. It seemed like the v1 model wasn't compatible with the version of tensorflow that is used (but only in some environments). If you pull from main, it should work now. Please let us know if it doesn't. Also, we always welcome people trying out different object detection models.
