### ISSUE TITLE
[PBI] - Have a tag for the project 

### ISSUE THREAD

**Issue by mrbrandao** [eclipse-chariott/chariott#171]
## Description

I'm currently working on creating an [RPM package](https://pagure.io/chariott-on-fedora/rpm-rust-chariott) for chariott, if we have a git tag could help significantly on the package creation, is there any plans on having a tag?
Any version tag might help, perhaps a [semver alpha, such as](https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) `0.1.0`  can help tremendously. 

## Acceptance criteria

have a git tag

**Comment by devkelley** [comment]
Hi @mrbrandao,

Thank you for reaching out! There are plans on adding a tag, I will be looking into doing this next week. We will be using the semantic versioning system. I will reach out here when it has been added.

**Comment by devkelley** [comment]
@mrbrandao I have added a git tag to the project now. You can see it here: https://github.com/eclipse-chariott/chariott/tags.

Let us know if you have any more questions
